### ISSUE TITLE
Read in boolean column type

### ISSUE THREAD

**Issue by firekg** [promised-ai/lace#38]
When loading in columns with "TRUE" / "FALSE" entries, lace produced the following error message: `Failed to build engine: NewEngineError(DataParseError(Codebook(UnableToInferColumnType { col_name: "<NAME OF COLUMN>" })))`

**Comment by BaxterEaves** [comment]
What is happening is that polars understands the data to be boolean, but we don't handle boolean `Series` internally. 

It would be pretty easy to shove the boolean data into a categorical type, but then the data for that column would be internally represented as `u8`. Maybe this isn't so bad, because String categories are already represented as u8, but it would be more difficult to make things work nicely with `pylace`. `pylace` uses the `value_map` in the `codebook` to convert between `String` and `u8` internally so the representation is invisible to the user, but we couldn't use the `value_map` for `bool` data because the `value_map` is for strings only.

What we probably should do is to implement a `Binary` `ColModel` variant which would be backed by `Bernoulli` components with `BetaPrior` with `Gamma` (or similar) on the α and β parameters. Maybe hyperpriors on binary data is overkill? I believe we have `Feature` implemented for `Column<bool, Bernoulli, Beta, ()>`, so if we don't want a prior, we could just expose that `Column` through `ColModel::Binary`

**Comment by BaxterEaves** [comment]
Looking over things, this will be a beast to implement. I'd like to do it for the 0.2.0 release, but it'll take too much time for 0.1.0.

**Comment by BaxterEaves** [comment]
Note that the category data type was added in #68
